<a href="https://colab.research.google.com/github/codingbjs/PythonBasic/blob/main/NumPy/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [1]:
import numpy as np

np.__version__

'1.23.5'

In [2]:
a0 = np.array(9)
print(a0)

9


In [3]:
a1 = np.array([1,3,5,7,9])
print(a1)

[1 3 5 7 9]


In [4]:
a1[2]

5

In [5]:
a1[1:3]

array([3, 5])

In [7]:
a2 = np.array([[1,2,3,], [4,5,6], [7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
a2[1]

array([4, 5, 6])

In [9]:
a2[1,1]

5

In [10]:
a2[:,1]

array([2, 5, 8])

In [11]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [13]:
a3[1]

array([[5, 6],
       [7, 8]])

In [14]:
a3[1,1]

array([7, 8])

In [15]:
a3[1,1,1]

8

In [16]:
a3[:,0,0]

array([1, 5, 9])

In [17]:
a3[:,:,0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [18]:
ar = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
ar.shape

(12,)

In [20]:
ar.ndim

1

In [21]:
ar.size

12

In [22]:
ar2 = ar.reshape(3,4)
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
ar2.shape

(3, 4)

In [25]:
ar2.ndim

2

In [26]:
ar2.size

12

In [27]:
ar3 = ar.reshape(3,2,2)
print(ar3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [28]:
ar3.shape

(3, 2, 2)

In [29]:
ar3.ndim

3

In [30]:
ar3.size

12

In [31]:
ar.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [32]:
ar2.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [33]:
ar2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
ar3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
ar3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [39]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.zeros([3,4])+9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.random.rand(3,2,2)

array([[[0.26767117, 0.12078827],
        [0.09324781, 0.75875598]],

       [[0.28311649, 0.32140945],
        [0.13682614, 0.94961701]],

       [[0.55167276, 0.53481601],
        [0.41914628, 0.42062239]]])

In [49]:
np.random.randint(1,45, size = (5,6))

array([[12, 30, 16, 11,  2, 18],
       [23, 22, 33, 25, 38, 37],
       [16, 38,  6, 29, 39,  4],
       [37, 40,  5, 40, 17, 43],
       [38,  6, 20, 35, 35, 44]])

In [50]:
np.random.seed(2045)
np.random.choice(np.arange(1,46), size=(5,6), replace = False)

array([[ 7, 32,  6, 41,  4, 34],
       [30, 28, 16,  5, 38, 33],
       [31, 13, 25, 23, 43, 12],
       [45,  8, 29, 22, 18,  9],
       [21, 20, 40,  2, 37, 39]])

In [52]:
ta = np.arange(1,10)
ta

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.random.shuffle(ta)
ta

array([7, 6, 5, 4, 3, 1, 8, 2, 9])