<a href="https://colab.research.google.com/github/codingbjs/PythonBasic/blob/main/NumPy/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np

np.__version__

'1.23.5'

In [ ]:
a0 = np.array(9)
print(a0)

9


In [ ]:
a1 = np.array([1,3,5,7,9])
print(a1)

[1 3 5 7 9]


In [ ]:
a1[2]

5

In [ ]:
a1[1:3]

array([3, 5])

In [ ]:
a2 = np.array([[1,2,3,], [4,5,6], [7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a2[1]

array([4, 5, 6])

In [ ]:
a2[1,1]

5

In [ ]:
a2[:,1]

array([2, 5, 8])

In [ ]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
a3[1]

array([[5, 6],
       [7, 8]])

In [ ]:
a3[1,1]

array([7, 8])

In [ ]:
a3[1,1,1]

8

In [ ]:
a3[:,0,0]

array([1, 5, 9])

In [ ]:
a3[:,:,0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [ ]:
ar = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
ar.shape

(12,)

In [ ]:
ar.ndim

1

In [ ]:
ar.size

12

In [ ]:
ar2 = ar.reshape(3,4)
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ar2.shape

(3, 4)

In [ ]:
ar2.ndim

2

In [ ]:
ar2.size

12

In [ ]:
ar3 = ar.reshape(3,2,2)
print(ar3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
ar3.shape

(3, 2, 2)

In [ ]:
ar3.ndim

3

In [ ]:
ar3.size

12

In [ ]:
ar.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
ar2.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
ar2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
ar3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
ar3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros([3,4])+9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,2,2)

array([[[0.26767117, 0.12078827],
        [0.09324781, 0.75875598]],

       [[0.28311649, 0.32140945],
        [0.13682614, 0.94961701]],

       [[0.55167276, 0.53481601],
        [0.41914628, 0.42062239]]])

In [ ]:
np.random.randint(1,45, size = (5,6))

array([[12, 30, 16, 11,  2, 18],
       [23, 22, 33, 25, 38, 37],
       [16, 38,  6, 29, 39,  4],
       [37, 40,  5, 40, 17, 43],
       [38,  6, 20, 35, 35, 44]])

In [ ]:
np.random.seed(2045)
np.random.choice(np.arange(1,46), size=(5,6), replace = False)

array([[ 7, 32,  6, 41,  4, 34],
       [30, 28, 16,  5, 38, 33],
       [31, 13, 25, 23, 43, 12],
       [45,  8, 29, 22, 18,  9],
       [21, 20, 40,  2, 37, 39]])

In [ ]:
ta = np.arange(1,10)
ta

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(ta)
ta

array([7, 6, 5, 4, 3, 1, 8, 2, 9])

In [3]:
a1 = np.array([85,93,75,97,69])
a2 = np.array([91,90,85,97,89])

a3 = np.array([[85,93,75],[90,84,97],[99,91,80]])

a1 + a2

array([176, 183, 160, 194, 158])

In [4]:
a1 - a2

array([ -6,   3, -10,   0, -20])

In [5]:
a1 * a2

array([7735, 8370, 6375, 9409, 6141])

In [6]:
a2 / a1

array([1.07058824, 0.96774194, 1.13333333, 1.        , 1.28985507])

In [7]:
a1 * 3

array([255, 279, 225, 291, 207])

In [8]:
a1 ** 2

array([7225, 8649, 5625, 9409, 4761])

In [9]:
a1.sum()

419

In [10]:
a2.mean()

90.4

In [11]:
a2.var()

15.040000000000001

In [12]:
a2.std()

3.8781438859330635

In [13]:
a2.min()

85

In [14]:
a3.min()

75

In [15]:
a3.min(axis=0)

array([85, 84, 75])

In [16]:
a3.min(axis=1, keepdims=True)

array([[75],
       [84],
       [80]])

In [17]:
a2.max()

97

In [18]:
a3.max()

99

In [19]:
a3.max(axis=0)

array([99, 93, 97])

In [20]:
a3.max(axis=1)

array([93, 97, 99])

In [21]:
a3.max(axis=1, keepdims=True)

array([[93],
       [97],
       [99]])

In [22]:
a1.cumsum()

array([ 85, 178, 253, 350, 419])

In [23]:
a1.cumprod()

array([        85,       7905,     592875,   57508875, 3968112375])

In [25]:
m1 = np.array([2,4,6,8]).reshape(2,2)
print(m1)

[[2 4]
 [6 8]]


In [26]:
m2 = np.array([3,5,7,9]).reshape(2,2)
print(m2)

[[3 5]
 [7 9]]


In [27]:
m1.dot(m2)

array([[ 34,  46],
       [ 74, 102]])

In [28]:
np.dot(m2, m1)

array([[ 36,  52],
       [ 68, 100]])

In [29]:
m1 * m2

array([[ 6, 20],
       [42, 72]])

In [30]:
m2 * m1

array([[ 6, 20],
       [42, 72]])

In [31]:
np.transpose(m1)

array([[2, 6],
       [4, 8]])

In [33]:
np.transpose(m2)

array([[3, 7],
       [5, 9]])

In [34]:
m2.T

array([[3, 7],
       [5, 9]])